set -x

python3 -m verl.trainer.main_vgpt_ppo \
    actor_rollout_ref.actor.interact=True \
    actor_rollout_ref.rollout.interact=True \
    processor.interact=True\
    processor.tokenizer.name=ctx_cnn \
    processor.tokenizer.path=null \
    actor_rollout_ref.model.path=null \
    data.max_prompt_length=1373 \
    data.max_response_length=651 \
    processor.bos_token_id=9006 \
    processor.eos_token_id=9007 \
    processor.pad_token_id=9007 \
    processor.tokens_per_frame=80 \
    processor.processor_type=ctx_msp \
    processor.max_length=2024 \
    data.video.segment_length=8 \
    \
    algorithm.adv_estimator=grpo \
    data.train_batch_size=128 \
    data.video.dataset_path=null \
    actor_rollout_ref.actor.optim.lr=5e-5 \
    actor_rollout_ref.model.use_remove_padding=False \
    actor_rollout_ref.actor.ppo_mini_batch_size=32 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=False \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.top_k=-1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=5 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name='verl_grpo_example_vgpt' \
    trainer.experiment_name='ctx_vgpt_msp8_no_test' \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.save_freq=50 \
    trainer.val_iters=10 \
    trainer.test_freq=-1 $@ | tee verl_vgpt.log